version: "3"
services:
  web:
    build: ./client
    ports:
      - "80:80"
    networks:
      - net-app
  server:
    build: ./server
    ports:
      - "8080:8080"
    external_links:
      - mongo
    networks:
      - net-app
  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - net-app
    volumes:
      - data-volume:/data/db

volumes:
  data-volume:
networks:
  net-app:
    driver: bridge
